<?php
/**
 * @file
 * Feeds: Import.io base functions.
 */

/**
 * Implements hook_feeds_plugins().
 */
function feeds_import_io_feeds_plugins() {
  $info = array();

  $info['FeedsImportIoFetcher'] = array(
    'name' => 'import.io Fetcher',
    'description' => 'Fetch data from import.io API.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'FeedsImportIoFetcher',
      'file' => 'FeedsImportIoFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_import_io') . '/plugins',
    ),
  );

  $info['FeedsImportIoParser'] = array(
    'name' => 'import.io Parser',
    'description' => 'Parse fetched data from import.io API.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsImportIoParser',
      'file' => 'FeedsImportIoParser.inc',
      'path' => drupal_get_path('module', 'feeds_import_io') . '/plugins',
    ),
  );

  return $info;
}
